// Builds the website into site/. No dependencies, just Node 18+.
//
//   node build.mjs
//
// Writes every .html page, sitemap.xml, robots.txt, site.webmanifest and PHOTOS.md.
// The CSS, JavaScript, fonts and images in site/ are edited directly, not generated.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { setAssetVersions } from './src/layout.mjs';
import { site } from './src/content/site.mjs';
import { photos, gallery, instagramTiles } from './src/content/photos.mjs';
import home from './src/pages/home.mjs';
import menus from './src/pages/menus.mjs';
import holiday from './src/pages/holiday.mjs';
import about from './src/pages/about.mjs';
import galleryPage from './src/pages/gallery.mjs';
import contact from './src/pages/contact.mjs';
import { thanks, notFound } from './src/pages/extra.mjs';

const root = dirname(fileURLToPath(import.meta.url));
const out = join(root, 'site');

const hash = (file) => createHash('sha256').update(readFileSync(join(out, file))).digest('hex').slice(0, 10);
setAssetVersions({ css: hash('css/site.css'), js: hash('js/site.js') });

// Straight apostrophes and quotes to typographic ones, in visible text only
// (never inside tags, <script> or <style>).
function typography(html) {
  return html
    .split(/(<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<[^>]+>)/g)
    .map((part, i) => {
      if (i % 2 === 1) return part; // a tag or a script/style block
      return part
        .replace(/(\w)'(\w)/g, '$1’$2') // don't, Aaron J's
        .replace(/(\w)'/g, '$1’') // guests'
        .replace(/'(\w)/g, '‘$1')
        .replace(/"(\S)/g, '“$1')
        .replace(/(\S)"/g, '$1”');
    })
    .join('');
}

const pages = {
  'index.html': home(),
  'menus.html': menus(),
  'holiday.html': holiday(),
  'about.html': about(),
  'gallery.html': galleryPage(),
  'contact.html': contact(),
  'thanks.html': thanks(),
  '404.html': notFound(),
};

for (const [file, html] of Object.entries(pages)) {
  writeFileSync(join(out, file), typography(html));
}

// Sitemap: the public pages only.
const today = new Date().toISOString().slice(0, 10);
const listed = [
  ['', '1.0'],
  ['menus.html', '0.9'],
  ['holiday.html', '0.9'],
  ['contact.html', '0.8'],
  ['about.html', '0.6'],
  ['gallery.html', '0.5'],
];
writeFileSync(
  join(out, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${listed.map(([p, pr]) => `  <url><loc>${site.url}/${p}</loc><lastmod>${today}</lastmod><priority>${pr}</priority></url>`).join('\n')}
</urlset>
`,
);

writeFileSync(join(out, 'robots.txt'), `User-agent: *\nDisallow: /thanks.html\n\nSitemap: ${site.url}/sitemap.xml\n`);

writeFileSync(
  join(out, 'site.webmanifest'),
  JSON.stringify(
    {
      name: site.name,
      short_name: "Aaron J's",
      start_url: '/',
      display: 'browser',
      background_color: '#0B0B0C',
      theme_color: '#0B0B0C',
      icons: [
        { src: 'images/icon-192.png', sizes: '192x192', type: 'image/png' },
        { src: 'images/icon-512.png', sizes: '512x512', type: 'image/png' },
      ],
    },
    null,
    2,
  ) + '\n',
);

// PHOTOS.md: the shot list, so whoever takes the photos knows what goes where.
const status = { flyer: 'From the flyer (low resolution)', made: 'Made by tools/brand-images.mjs' };
const rows = [
  ...Object.values(photos).map((p) => [p, p.where]),
  ...gallery.map((g) => [g, 'Gallery page']),
  ...instagramTiles.map((t) => [t, 'Home page, Instagram section']),
].map(([p, where]) => [p.file, status[p.source] ?? '**Placeholder**', `${p.w} x ${p.h}`, where, p.shot]);
writeFileSync(
  join(root, 'PHOTOS.md'),
  `# Photo shot list

Most photos on the site are labeled placeholders until you replace them. A few are real but
low resolution, cut from the Aaron J's flyers; send the originals and they'll look sharper.
To swap one in, save the real photo over the file in \`site/images/\` with the **same file name**.
No code changes needed.

- Export as JPG, about 80% quality. Keep each file under 400 KB (the hero under 600 KB).
- Sizes below are what to export at. A slightly different shape is fine; the layout crops to fit,
  so keep the subject near the center.
- After swapping, update the description (the \`alt\` text) in \`src/content/photos.mjs\` if the
  photo shows something different, then run \`node build.mjs\`.

This file is generated by \`node build.mjs\` from \`src/content/photos.mjs\`.

| File | Now | Size (px) | Where it shows | What to shoot |
|---|---|---|---|---|
${rows.map((r) => `| \`${r[0]}\` | ${r[1]} | ${r[2]} | ${r[3]} | ${r[4]} |`).join('\n')}

Logo and icons:

| File | What it is |
|---|---|
| \`logo.png\` | The logo, cut out of the flyer. It works, but the original logo file (PNG with a transparent background, or SVG) would be sharper. Save it over this file, then run \`node tools/brand-images.mjs\`. |
| \`favicon-32.png\`, \`icon-192.png\`, \`icon-512.png\`, \`apple-touch-icon.png\` | Browser tab and home screen icons, made from the logo by \`node tools/brand-images.mjs\`. |
`,
);

console.log(`Built ${Object.keys(pages).length} pages into site/`);
