import { SPACE, type Theme, type ThemeType } from './tokens';

/**
 * The switchable themes. N (Original colors, catalog layout) is the default; L is its light version.
 *
 * Font family strings must match the keys loaded in `fonts.ts`.
 */

const baseType: ThemeType = {
  hero: { fontSize: 34, lineHeight: 40, letterSpacing: -0.5 },
  h1: { fontSize: 26, lineHeight: 32, letterSpacing: -0.3 },
  h2: { fontSize: 20, lineHeight: 26 },
  h3: { fontSize: 17, lineHeight: 22 },
  body: { fontSize: 15, lineHeight: 22 },
  small: { fontSize: 13, lineHeight: 18 },
  caption: { fontSize: 11, lineHeight: 15 },
  label: { fontSize: 11, lineHeight: 14, letterSpacing: 1.2 },
  number: { fontSize: 28, lineHeight: 32 },
};

/** O: Original. The prototype's own look: near-black, red primary, green trust, gold events, Bebas Neue + Syne. */
const O: Theme = {
  id: 'O',
  name: 'Original',
  tagline: "The I'm In prototype look",
  mode: 'dark',
  colors: {
    bg: '#0C0C0C',
    surface: '#161616',
    surfaceAlt: '#1E1E1E',
    border: 'rgba(255, 255, 255, 0.08)',
    borderStrong: '#333333',
    text: '#F5F5F5',
    textMuted: 'rgba(245, 245, 245, 0.62)',
    textSubtle: 'rgba(245, 245, 245, 0.5)',
    primary: '#D62828',
    primaryText: '#FF5C5C',
    onPrimary: '#FFFFFF',
    secondary: '#D4AF37',
    onSecondary: '#0C0C0C',
    trust: '#4ADE80',
    onTrust: '#052E16',
    ai: '#64A0FF',
    onAi: '#0C0C0C',
    success: '#4ADE80',
    warning: '#D4AF37',
    danger: '#FF6B6B',
    onDanger: '#1A0000',
    sponsored: '#D4AF37',
    onSponsored: '#0C0C0C',
    tabBar: '#0C0C0C',
    tabActive: '#FF4D4D',
    tabInactive: 'rgba(245, 245, 245, 0.5)',
    overlay: 'rgba(0, 0, 0, 0.75)',
  },
  fonts: {
    display: 'BebasNeue_400Regular',
    displayBold: 'BebasNeue_400Regular',
    body: 'Syne_400Regular',
    bodyMedium: 'Syne_600SemiBold',
    bodyBold: 'Syne_700Bold',
    mono: 'JetBrainsMono_500Medium',
  },
  // Bebas Neue is a tall, condensed all-caps face, so display sizes run larger.
  type: {
    ...baseType,
    hero: { fontSize: 48, lineHeight: 50, letterSpacing: 1 },
    h1: { fontSize: 34, lineHeight: 38, letterSpacing: 0.8 },
    h2: { fontSize: 26, lineHeight: 30, letterSpacing: 0.6 },
    number: { fontSize: 38, lineHeight: 40, letterSpacing: 0.5 },
  },
  radius: { sm: 8, md: 11, lg: 14, xl: 20, pill: 999 },
  space: SPACE,
  borderWidth: { hairline: 1, regular: 1, strong: 1.5 },
  shadow: {
    card: '0px 0px 0px rgba(0,0,0,0)',
    raised: '0px 12px 32px rgba(0,0,0,0.5)',
    pressed: '0px 0px 0px rgba(0,0,0,0)',
  },
  style: { section: 'plain', badge: 'pill', uppercaseLabels: true, monoNumbers: false },
};

/** A: Warm Editorial. Warm charcoal, ivory, plum, serif headlines. */
const A: Theme = {
  id: 'A',
  name: 'Warm Editorial',
  tagline: 'A premium magazine',
  mode: 'dark',
  colors: {
    bg: '#1C1917',
    surface: '#262220',
    surfaceAlt: '#302B28',
    border: '#3D3632',
    borderStrong: '#6B5F57',
    text: '#F6F0E6',
    textMuted: '#C4B8A8',
    textSubtle: '#8F8578',
    primary: '#B8466B',
    primaryText: '#E07A9A',
    onPrimary: '#FFF6F0',
    secondary: '#C9A36B',
    onSecondary: '#1C1917',
    trust: '#C9A36B',
    onTrust: '#1C1917',
    ai: '#B79CE0',
    onAi: '#1C1917',
    success: '#8FBF8A',
    warning: '#E0B060',
    danger: '#E0645C',
    onDanger: '#1C1917',
    sponsored: '#C9A36B',
    onSponsored: '#1C1917',
    tabBar: '#1C1917',
    tabActive: '#F6F0E6',
    tabInactive: '#8F8578',
    overlay: 'rgba(12, 10, 9, 0.72)',
  },
  fonts: {
    display: 'Fraunces_600SemiBold',
    displayBold: 'Fraunces_700Bold',
    body: 'DMSans_400Regular',
    bodyMedium: 'DMSans_500Medium',
    bodyBold: 'DMSans_700Bold',
    mono: 'JetBrainsMono_500Medium',
  },
  type: baseType,
  radius: { sm: 6, md: 10, lg: 14, xl: 20, pill: 999 },
  space: SPACE,
  borderWidth: { hairline: 1, regular: 1, strong: 1.5 },
  shadow: {
    card: '0px 8px 24px rgba(0,0,0,0.28)',
    raised: '0px 12px 32px rgba(0,0,0,0.36)',
    pressed: '0px 2px 8px rgba(0,0,0,0.3)',
  },
  style: { section: 'plain', badge: 'pill', uppercaseLabels: true, monoNumbers: false },
};

/** B: DC Night. Navy-black, amber-gold primary, electric blue only for AI. */
const B: Theme = {
  id: 'B',
  name: 'DC Night',
  tagline: 'Confident, cosmopolitan',
  mode: 'dark',
  colors: {
    bg: '#0A0F1C',
    surface: '#121A2B',
    surfaceAlt: '#1A2438',
    border: '#243049',
    borderStrong: '#3A4A6B',
    text: '#EEF2FA',
    textMuted: '#A7B2C8',
    textSubtle: '#76819A',
    primary: '#F2B33D',
    primaryText: '#F2B33D',
    onPrimary: '#1A1200',
    secondary: '#F2B33D',
    onSecondary: '#1A1200',
    trust: '#F2B33D',
    onTrust: '#1A1200',
    ai: '#4C95FF',
    onAi: '#000A1F',
    success: '#4ADE80',
    warning: '#F2B33D',
    danger: '#FF6B6B',
    onDanger: '#1A0000',
    sponsored: '#F2B33D',
    onSponsored: '#1A1200',
    tabBar: '#0A0F1C',
    tabActive: '#F2B33D',
    tabInactive: '#76819A',
    overlay: 'rgba(4, 7, 14, 0.75)',
  },
  fonts: {
    display: 'SpaceGrotesk_600SemiBold',
    displayBold: 'SpaceGrotesk_700Bold',
    body: 'DMSans_400Regular',
    bodyMedium: 'DMSans_500Medium',
    bodyBold: 'DMSans_700Bold',
    mono: 'JetBrainsMono_500Medium',
  },
  type: baseType,
  radius: { sm: 8, md: 12, lg: 16, xl: 22, pill: 999 },
  space: SPACE,
  borderWidth: { hairline: 1, regular: 1, strong: 1.5 },
  shadow: {
    card: '0px 8px 24px rgba(0,0,0,0.35)',
    raised: '0px 12px 32px rgba(0,0,0,0.45)',
    pressed: '0px 2px 8px rgba(0,0,0,0.35)',
  },
  style: { section: 'plain', badge: 'pill', uppercaseLabels: true, monoNumbers: false },
};

/** C: Blush and Gold. Dark base with blush, gold for trust, frosted cards. */
const C: Theme = {
  id: 'C',
  name: 'Blush and Gold',
  tagline: 'Soft, warm, a little luxe',
  mode: 'dark',
  colors: {
    bg: '#16110F',
    surface: 'rgba(255, 228, 225, 0.07)',
    surfaceAlt: 'rgba(255, 228, 225, 0.11)',
    border: 'rgba(255, 228, 225, 0.14)',
    borderStrong: 'rgba(255, 228, 225, 0.3)',
    text: '#FBEFEA',
    textMuted: '#D4BDB5',
    textSubtle: '#9C8A84',
    primary: '#F2A7B4',
    primaryText: '#F2A7B4',
    onPrimary: '#2A0E14',
    secondary: '#D9B26F',
    onSecondary: '#211606',
    trust: '#D9B26F',
    onTrust: '#211606',
    ai: '#C7B5FF',
    onAi: '#170F2E',
    success: '#9FD8A8',
    warning: '#E8C07A',
    danger: '#FF7A7A',
    onDanger: '#2A0000',
    sponsored: '#D9B26F',
    onSponsored: '#211606',
    tabBar: '#16110F',
    tabActive: '#F2A7B4',
    tabInactive: '#9C8A84',
    overlay: 'rgba(10, 6, 5, 0.72)',
  },
  fonts: {
    display: 'Fraunces_500Medium',
    displayBold: 'Fraunces_600SemiBold',
    body: 'DMSans_400Regular',
    bodyMedium: 'DMSans_500Medium',
    bodyBold: 'DMSans_700Bold',
    mono: 'JetBrainsMono_500Medium',
  },
  type: baseType,
  radius: { sm: 10, md: 16, lg: 22, xl: 28, pill: 999 },
  space: SPACE,
  borderWidth: { hairline: 1, regular: 1, strong: 1 },
  shadow: {
    card: '0px 10px 30px rgba(0,0,0,0.25)',
    raised: '0px 14px 40px rgba(0,0,0,0.35)',
    pressed: '0px 3px 10px rgba(0,0,0,0.25)',
  },
  style: { section: 'glass', badge: 'pill', uppercaseLabels: false, monoNumbers: false },
};

/** D: Trust as Design. Light, verified green primary, mono numbers, credential badges. */
const D: Theme = {
  id: 'D',
  name: 'Trust as Design',
  tagline: 'Closer to fintech than social',
  mode: 'light',
  colors: {
    bg: '#FAFAF7',
    surface: '#FFFFFF',
    surfaceAlt: '#F1F2EE',
    border: '#E3E5DF',
    borderStrong: '#C5C9C0',
    text: '#111512',
    textMuted: '#4F5750',
    textSubtle: '#646C65',
    primary: '#0F7A4A',
    primaryText: '#0F7A4A',
    onPrimary: '#FFFFFF',
    secondary: '#111512',
    onSecondary: '#FFFFFF',
    trust: '#0F7A4A',
    onTrust: '#FFFFFF',
    ai: '#5B4BDB',
    onAi: '#FFFFFF',
    success: '#0F7A4A',
    warning: '#A15C00',
    danger: '#C62828',
    onDanger: '#FFFFFF',
    sponsored: '#8A5A00',
    onSponsored: '#FFFFFF',
    tabBar: '#FFFFFF',
    tabActive: '#0F7A4A',
    tabInactive: '#646C65',
    overlay: 'rgba(17, 21, 18, 0.45)',
  },
  fonts: {
    display: 'DMSans_700Bold',
    displayBold: 'DMSans_800ExtraBold',
    body: 'DMSans_400Regular',
    bodyMedium: 'DMSans_500Medium',
    bodyBold: 'DMSans_700Bold',
    mono: 'JetBrainsMono_500Medium',
  },
  type: baseType,
  radius: { sm: 6, md: 10, lg: 12, xl: 16, pill: 999 },
  space: SPACE,
  borderWidth: { hairline: 1, regular: 1, strong: 1.5 },
  shadow: {
    card: '0px 1px 2px rgba(17,21,18,0.06)',
    raised: '0px 6px 20px rgba(17,21,18,0.08)',
    pressed: '0px 0px 0px rgba(0,0,0,0)',
  },
  style: { section: 'ledger', badge: 'credential', uppercaseLabels: true, monoNumbers: true },
};



/**
 * The house type: Figtree (Dominique's pick), heavy and tight for headlines,
 * plain and readable for everything else.
 */
const guestType: ThemeType = {
  hero: { fontSize: 34, lineHeight: 39, letterSpacing: -0.8 },
  h1: { fontSize: 26, lineHeight: 31, letterSpacing: -0.5 },
  h2: { fontSize: 19, lineHeight: 24, letterSpacing: -0.3 },
  h3: { fontSize: 17, lineHeight: 22, letterSpacing: -0.2 },
  body: { fontSize: 16, lineHeight: 22, letterSpacing: -0.1 },
  small: { fontSize: 14, lineHeight: 19 },
  caption: { fontSize: 12, lineHeight: 16 },
  label: { fontSize: 13, lineHeight: 18, letterSpacing: -0.1 },
  number: { fontSize: 30, lineHeight: 34, letterSpacing: -0.6 },
};
// Headlines in Bold, not ExtraBold/Black: heavy type everywhere reads as loud
// rather than polished. The black weight is kept for the one hero line.
const guestFonts = {
  display: 'Figtree_700Bold',
  displayBold: 'Figtree_800ExtraBold',
  body: 'Figtree_400Regular',
  bodyMedium: 'Figtree_600SemiBold',
  bodyBold: 'Figtree_700Bold',
  mono: 'Figtree_600SemiBold',
} as const;
const guestStyle: Theme['style'] = {
  section: 'poster',
  badge: 'pill',
  uppercaseLabels: false,
  monoNumbers: false,
  monoLabels: false,
  surface: 'flat',
  controls: 'ticket',
};

/** L: Original Light. Instagram-style light: pure white, soft grays, the original green. */
const L: Theme = {
  id: 'L',
  name: 'Original Light',
  tagline: 'Light, with the original green',
  mode: 'light',
  colors: {
    bg: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceAlt: '#EFEFEF',
    border: '#DBDBDB',
    borderStrong: '#C7C7C7',
    text: '#000000',
    textMuted: '#5E5E5E',
    textSubtle: '#6B6B6B',
    primary: '#0F7A4A',
    primaryText: '#0F7A4A',
    onPrimary: '#FFFFFF',
    secondary: '#111512',
    onSecondary: '#FFFFFF',
    trust: '#0F7A4A',
    onTrust: '#FFFFFF',
    ai: '#5B4BDB',
    onAi: '#FFFFFF',
    success: '#0F7A4A',
    warning: '#A15C00',
    danger: '#C62828',
    onDanger: '#FFFFFF',
    sponsored: '#8A5A00',
    onSponsored: '#FFFFFF',
    tabBar: '#FFFFFF',
    tabActive: '#000000',
    tabInactive: '#6B6B6B',
    overlay: 'rgba(0, 0, 0, 0.45)',
  },
  fonts: guestFonts,
  type: guestType,
  radius: { sm: 4, md: 8, lg: 12, xl: 16, pill: 999 },
  space: SPACE,
  borderWidth: { hairline: 1, regular: 1, strong: 1.5 },
  shadow: {
    card: '0px 1px 2px rgba(30,27,24,0.04), 0px 6px 18px rgba(30,27,24,0.05)',
    raised: '0px 10px 30px rgba(30,27,24,0.10)',
    pressed: '0px 0px 0px rgba(0,0,0,0)',
  },
  style: guestStyle,
};

/**
 * N: Original. The default. Instagram-style dark (pure black, its grays and
 * hairlines) with the app's red, gold and green: flat surfaces, poster
 * headlines and square-cut controls.
 */
const N: Theme = {
  id: 'N',
  name: 'Original',
  tagline: 'Near-black, red and gold',
  mode: 'dark',
  colors: {
    bg: '#000000',
    surface: '#121212',
    surfaceAlt: '#262626',
    border: '#262626',
    borderStrong: '#363636',
    text: '#F5F5F5',
    textMuted: '#A8A8A8',
    textSubtle: '#8E8E8E',
    primary: '#D62828',
    primaryText: '#FF5C5C',
    onPrimary: '#FFFFFF',
    secondary: '#D4AF37',
    onSecondary: '#000000',
    trust: '#4ADE80',
    onTrust: '#052E16',
    ai: '#64A0FF',
    onAi: '#0C0C0C',
    success: '#4ADE80',
    warning: '#D4AF37',
    danger: '#FF6B6B',
    onDanger: '#1A0000',
    sponsored: '#D4AF37',
    onSponsored: '#0C0C0C',
    tabBar: '#000000',
    tabActive: '#F5F5F5',
    tabInactive: '#8E8E8E',
    overlay: 'rgba(0, 0, 0, 0.75)',
  },
  fonts: guestFonts,
  type: guestType,
  radius: { sm: 4, md: 8, lg: 12, xl: 16, pill: 999 },
  space: SPACE,
  borderWidth: { hairline: 1, regular: 1, strong: 1.5 },
  shadow: {
    card: '0px 0px 0px rgba(0,0,0,0)',
    raised: '0px 10px 30px rgba(0,0,0,0.45)',
    pressed: '0px 0px 0px rgba(0,0,0,0)',
  },
  style: guestStyle,
};

export const THEMES: Record<Theme['id'], Theme> = { L, N, O, A, B, C, D };
export const THEME_ORDER: Theme['id'][] = ['N', 'L', 'O', 'A', 'B', 'C', 'D'];
export const DEFAULT_THEME_ID: Theme['id'] = 'N';
