// Every dish on the site, defined once.
// Menus (menus.mjs) and the holiday page (holiday.mjs) point at these by id,
// so a dish's ingredients and allergens can't drift between pages.
//
// `allergens` must match what's in `ingredients`. `node tools/check.mjs`
// scans the ingredient text for allergen words and fails if the two disagree.
//
// Allergen names: dairy, eggs, wheat, shellfish, fish, tree nuts, peanuts, soy, sesame, mustard.
//
// `source: 'thanksgiving-2026'` marks recipes copied from the printed Aaron J's
// Thanksgiving 2026 menu. Everything else is a draft for Chef Aaron to confirm.
// Optional fields: `note` (shown under the allergens), `spicy: true`.

// Shared sub-recipes, so they read the same everywhere.
const MAYO = 'mayonnaise (canola oil, egg yolks, distilled vinegar, lemon juice, salt)';
const HOT_SAUCE = 'hot sauce (aged cayenne peppers, distilled vinegar, salt, garlic)';
const CHICKEN_STOCK = 'chicken stock (chicken bones, water, onion, carrot, celery)';
const CAJUN = 'Cajun seasoning (paprika, garlic, onion, cayenne, oregano, thyme, black pepper, salt)';
const PIE_CRUST = 'all-butter crust (all-purpose wheat flour, butter, ice water, sugar, salt)';

export const dishes = {
  // ---------- Mains ----------
  'short-ribs': {
    name: 'Braised short ribs',
    description:
      'Bone-in short ribs braised with red wine, tomato paste, onion, carrot, celery, garlic and thyme.',
    ingredients: [
      'bone-in beef short ribs',
      'onion',
      'carrot',
      'celery',
      'garlic',
      'tomato paste',
      'red wine',
      'beef stock',
      'all-purpose flour',
      'thyme',
      'bay leaf',
      'black pepper',
    ],
    allergens: ['wheat'],
    source: 'thanksgiving-2026',
  },
  'baked-chicken': {
    name: 'Baked or grilled chicken',
    description:
      'Bone-in chicken seasoned with garlic, lemon, rosemary and paprika, baked or grilled.',
    ingredients: [
      'bone-in chicken thighs and breasts',
      'olive oil',
      'garlic',
      'lemon',
      'fresh rosemary',
      'fresh thyme',
      'paprika',
      'onion powder',
      'kosher salt',
      'black pepper',
    ],
    allergens: [],
  },
  'lemon-salmon': {
    name: 'Lemon herbed salmon',
    description: 'Salmon fillets roasted with lemon, garlic, dill and parsley, finished with a little butter.',
    ingredients: [
      'Atlantic salmon',
      'lemon',
      'garlic',
      'fresh dill',
      'parsley',
      'fresh thyme',
      'olive oil',
      'butter',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['fish', 'dairy'],
  },
  'surf-and-turf': {
    name: 'Surf and turf',
    description: 'Seared sirloin, sliced, next to shrimp sautéed in garlic butter with lemon and a little Cajun spice.',
    ingredients: [
      'beef sirloin',
      'shrimp',
      'butter',
      'garlic',
      'lemon',
      'parsley',
      CAJUN,
      'olive oil',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['shellfish', 'dairy'],
  },
  'cajun-seafood': {
    name: 'Cajun shrimp and crab',
    description:
      'Crab clusters, shrimp and andouille sausage in a Cajun garlic butter sauce with peppers and onion.',
    ingredients: [
      'crab clusters',
      'shrimp',
      'andouille sausage (pork, salt, garlic, paprika, cayenne, black pepper)',
      'butter',
      'garlic',
      'yellow onion',
      'red and green bell peppers',
      CAJUN,
      'crushed red pepper',
      'lemon',
      'parsley',
    ],
    allergens: ['shellfish', 'dairy'],
  },
  'crab-stuffed-shrimp': {
    name: 'Crab-stuffed shrimp',
    description: 'Jumbo shrimp stuffed with lump crab, cream cheese and buttered breadcrumbs, baked with Old Bay, lemon and garlic.',
    ingredients: ['jumbo shrimp', 'lump crab meat', 'cream cheese', 'breadcrumbs', 'butter', 'Old Bay', 'lemon', 'parsley', 'garlic'],
    // The printed menu lists egg for this dish, though no ingredient shows it. Kept, because
    // listing an allergen that may not be there is safe; leaving one off is not.
    allergens: ['shellfish', 'dairy', 'wheat', 'eggs'],
    note: 'Prepared separately from the rest of the menu.',
    source: 'thanksgiving-2026',
  },
  'fried-chicken': {
    name: 'Southern fried chicken',
    description: 'Bone-in chicken marinated in buttermilk and hot sauce, seasoned and fried crisp.',
    ingredients: [
      'chicken thighs and drumsticks',
      'buttermilk',
      HOT_SAUCE,
      'all-purpose wheat flour',
      'cornstarch',
      'kosher salt',
      'black pepper',
      'smoked paprika',
      'garlic powder',
      'onion powder',
      'cayenne pepper',
      'canola oil for frying',
    ],
    allergens: ['dairy', 'wheat'],
  },
  'fried-fish': {
    name: 'Fried fish',
    description:
      'Whiting or catfish in a seasoned cornmeal crust, fried golden. Lemon and tartar sauce on the side.',
    ingredients: [
      'whiting or catfish fillets',
      'yellow mustard',
      HOT_SAUCE,
      'yellow cornmeal',
      'all-purpose wheat flour',
      CAJUN,
      'canola oil for frying',
      'lemon',
      `tartar sauce (${MAYO}, dill relish, lemon juice, onion, parsley)`,
    ],
    allergens: ['fish', 'eggs', 'wheat', 'mustard'],
  },
  'smoked-turkey': {
    name: 'Smoked turkey',
    description: 'Rubbed with garlic, paprika, butter and fresh thyme and smoked over hardwood.',
    ingredients: ['whole turkey', 'kosher salt', 'black pepper', 'garlic', 'onion powder', 'paprika', 'butter', 'fresh thyme', 'hardwood smoke'],
    allergens: ['dairy'],
    source: 'thanksgiving-2026',
  },
  'jerk-turkey': {
    name: 'Jerk turkey',
    description: 'Marinated in scotch bonnet, allspice, thyme, scallion, ginger and lime.',
    ingredients: [
      'turkey',
      'scotch bonnet peppers',
      'allspice',
      'fresh thyme',
      'scallion',
      'ginger',
      'garlic',
      'brown sugar',
      'soy sauce (contains wheat)',
      'lime juice',
      'cinnamon',
      'nutmeg',
    ],
    allergens: ['soy', 'wheat'],
    spicy: true,
    source: 'thanksgiving-2026',
  },
  'fried-turkey': {
    name: 'Fried turkey',
    description: 'Seasoned with paprika, cayenne and Cajun spice, then fried.',
    ingredients: ['whole turkey', 'garlic powder', 'onion powder', 'paprika', 'cayenne', 'black pepper', 'salt', 'Cajun seasoning', 'frying oil'],
    allergens: [],
    source: 'thanksgiving-2026',
  },
  ham: {
    name: 'Glazed ham',
    description:
      'Bone-in smoked ham glazed with brown sugar, pineapple juice, honey and Dijon, studded with cloves, and dressed with pineapple rings and cherries.',
    ingredients: [
      'bone-in smoked ham',
      'brown sugar',
      'pineapple juice',
      'honey',
      'Dijon mustard',
      'whole cloves',
      'black pepper',
      'garnish: pineapple rings, maraschino cherries, parsley',
    ],
    allergens: ['mustard'],
    source: 'thanksgiving-2026',
  },
  'turkey-wings': {
    name: 'Smothered turkey wings',
    description: 'Turkey wings baked until tender and smothered in onion and sage gravy.',
    ingredients: [
      'turkey wings',
      'yellow onion',
      'celery',
      'garlic',
      'all-purpose wheat flour',
      CHICKEN_STOCK,
      'butter',
      'fresh sage',
      'fresh thyme',
      'smoked paprika',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['dairy', 'wheat'],
  },

  // ---------- Appetizers (from the Aaron J's menu flyer; ingredients are drafts) ----------
  'oxtail-biscuits': {
    name: 'Oxtail-stuffed biscuits',
    description: 'Buttermilk biscuits filled with tender braised oxtail.',
    ingredients: [
      'buttermilk biscuits (all-purpose wheat flour, butter, buttermilk, baking powder, salt)',
      'beef oxtails',
      'onion',
      'garlic',
      'fresh thyme',
      'allspice',
      'brown sugar',
      'tomato paste',
      'beef stock',
      'all-purpose flour',
      'black pepper',
    ],
    allergens: ['wheat', 'dairy'],
  },
  'shrimp-kebabs': {
    name: 'Shrimp kebabs',
    description: 'Seasoned shrimp skewered with peppers and red onion, grilled and finished with lemon.',
    ingredients: ['shrimp', 'bell peppers', 'red onion', 'olive oil', 'garlic', 'lemon', CAJUN, 'parsley'],
    allergens: ['shellfish'],
  },
  'smoked-wings': {
    name: 'Smoked wings',
    description: 'Smoked chicken wings in lemon pepper, buffalo (hot or mild) or garlic Parmesan.',
    ingredients: [
      'chicken wings',
      'dry rub (paprika, garlic powder, onion powder, brown sugar, salt, black pepper)',
      'hardwood smoke',
      'lemon pepper sauce (butter, lemon zest, black pepper)',
      `buffalo sauce (${HOT_SAUCE}, butter)`,
      'garlic Parmesan sauce (butter, garlic, Parmesan, parsley)',
    ],
    allergens: ['dairy'],
  },
  'fried-pickles': {
    name: 'Fried pickles',
    description: 'Dill pickle chips in a seasoned cornmeal crust, fried crisp, with ranch.',
    ingredients: [
      'dill pickle chips',
      'buttermilk',
      'all-purpose wheat flour',
      'yellow cornmeal',
      CAJUN,
      'canola oil for frying',
      `ranch (buttermilk, ${MAYO}, sour cream, garlic, dill, parsley)`,
    ],
    allergens: ['dairy', 'wheat', 'eggs'],
  },
  'crab-mushrooms': {
    name: 'Crab-stuffed mushrooms',
    description: 'Mushroom caps filled with lump crab, cream cheese and Parmesan, baked golden.',
    ingredients: [
      'cremini mushrooms',
      'lump crab meat',
      'cream cheese',
      'breadcrumbs',
      'Parmesan',
      'butter',
      'garlic',
      'Old Bay',
      'parsley',
      'lemon',
    ],
    allergens: ['shellfish', 'dairy', 'wheat'],
  },
  'crab-shrimp-eggrolls': {
    name: 'Crab and shrimp egg rolls',
    description: 'Crisp egg rolls filled with crab, shrimp and cabbage, with sweet chili sauce.',
    ingredients: [
      'egg roll wrappers (wheat flour, water, eggs, salt)',
      'crab meat',
      'shrimp',
      'green cabbage',
      'carrot',
      'scallions',
      'garlic',
      'ginger',
      'soy sauce (contains wheat)',
      'sesame oil',
      'canola oil for frying',
      'sweet chili sauce (chili peppers, sugar, vinegar, garlic)',
    ],
    allergens: ['shellfish', 'wheat', 'eggs', 'soy', 'sesame'],
  },
  'bacon-scallops': {
    name: 'Bacon-wrapped scallops',
    description: 'Sea scallops wrapped in crisp bacon, glazed and finished with fresh herbs.',
    ingredients: [
      'sea scallops',
      'bacon (pork, water, salt, sugar, sodium nitrite)',
      'brown sugar',
      'honey',
      'garlic',
      'black pepper',
      'chives',
      'parsley',
    ],
    allergens: ['shellfish'],
  },

  // ---------- Salads (from the Aaron J's menu flyer; ingredients are drafts) ----------
  'garden-salad': {
    name: 'Garden salad',
    description: 'Mixed greens, cucumber, grape tomatoes, red onion and carrot with croutons. Ranch or Italian dressing.',
    ingredients: [
      'romaine and mixed greens',
      'cucumber',
      'grape tomatoes',
      'red onion',
      'carrot',
      'croutons (bread (wheat flour, yeast, salt), olive oil, garlic)',
      `buttermilk ranch (buttermilk, ${MAYO}, sour cream, garlic, dill, parsley)`,
      'Italian vinaigrette (olive oil, red wine vinegar, garlic, oregano)',
    ],
    allergens: ['wheat', 'dairy', 'eggs'],
  },
  'caesar-salad': {
    name: 'Caesar salad',
    description: 'Romaine, shaved Parmesan and garlic croutons in Caesar dressing.',
    ingredients: [
      'romaine',
      'Parmesan',
      'croutons (bread (wheat flour, yeast, salt), olive oil, garlic)',
      `Caesar dressing (${MAYO}, Parmesan, lemon juice, garlic, Dijon mustard, anchovy, Worcestershire sauce, black pepper)`,
    ],
    allergens: ['dairy', 'wheat', 'eggs', 'fish', 'mustard'],
  },
  'cobb-salad': {
    name: 'Cobb salad',
    description: 'Chopped romaine with grilled chicken, bacon, egg, avocado, tomato and blue cheese, with ranch.',
    ingredients: [
      'romaine',
      'grilled chicken',
      'bacon (pork, water, salt, sugar, sodium nitrite)',
      'hard-boiled eggs',
      'avocado',
      'grape tomatoes',
      'blue cheese',
      'red onion',
      `buttermilk ranch (buttermilk, ${MAYO}, sour cream, garlic, dill, parsley)`,
    ],
    allergens: ['eggs', 'dairy'],
  },

  'garlic-mashed': {
    name: 'Garlic mashed potatoes with red wine gravy',
    description: 'Russet potatoes mashed with butter, cream and roasted garlic, under red wine gravy.',
    ingredients: [
      'russet potatoes',
      'butter',
      'heavy cream',
      'roasted garlic',
      'salt',
      'white pepper',
      'red wine gravy (red wine, beef stock, butter, all-purpose flour, shallot, thyme, black pepper)',
    ],
    allergens: ['dairy', 'wheat'],
  },

  // ---------- Brunch ----------
  'shrimp-and-grits': {
    name: 'Shrimp and grits',
    description:
      'Stone-ground grits with white cheddar and butter, under shrimp cooked with peppers, onion and Cajun spice in a pan gravy.',
    ingredients: [
      'shrimp',
      'stone-ground white grits',
      'white cheddar',
      'butter',
      'heavy cream',
      CHICKEN_STOCK,
      'yellow onion',
      'green bell pepper',
      'garlic',
      'all-purpose wheat flour',
      CAJUN,
      'smoked paprika',
      'scallions',
      'lemon',
    ],
    allergens: ['shellfish', 'dairy', 'wheat'],
  },
  'chicken-and-waffles': {
    name: 'Chicken and waffles',
    description: 'Fried chicken and buttermilk waffles with syrup, butter and fresh strawberries.',
    ingredients: [
      'chicken thighs and drumsticks',
      'buttermilk',
      HOT_SAUCE,
      'all-purpose wheat flour',
      'cornstarch',
      'kosher salt',
      'black pepper',
      'smoked paprika',
      'canola oil for frying',
      'buttermilk waffles (all-purpose wheat flour, buttermilk, eggs, butter, sugar, baking powder, baking soda, vanilla extract, salt)',
      'maple syrup',
      'strawberries',
      'butter',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  omelettes: {
    name: 'Cooked-to-order omelettes',
    description:
      'Omelettes made to order with cheddar, peppers, onion, spinach, tomato, mushrooms, turkey sausage or ham.',
    ingredients: [
      'eggs',
      'butter',
      'cheddar',
      'green and red bell peppers',
      'yellow onion',
      'spinach',
      'tomatoes',
      'mushrooms',
      'turkey sausage (turkey, salt, sage, black pepper, red pepper)',
      'ham (pork, water, salt, sugar, sodium nitrite)',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['eggs', 'dairy'],
  },
  'mini-quiche': {
    name: 'Handmade mini quiche',
    description: 'Two-bite quiches in an all-butter crust. Spinach and cheddar, or ham and Swiss.',
    ingredients: [
      PIE_CRUST,
      'eggs',
      'heavy cream',
      'whole milk',
      'spinach',
      'cheddar',
      'Swiss cheese',
      'ham (pork, water, salt, sugar, sodium nitrite)',
      'yellow onion',
      'nutmeg',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },

  // ---------- Wedding cocktail hour ----------
  'shrimp-grits': {
    name: 'Shrimp and grits cups',
    description:
      'Small cups of cheddar grits topped with a seared shrimp.',
    ingredients: [
      'shrimp',
      'stone-ground white grits',
      'white cheddar',
      'butter',
      'heavy cream',
      CHICKEN_STOCK,
      'garlic',
      'smoked paprika',
      CAJUN,
      'lemon',
      'scallions',
    ],
    allergens: ['shellfish', 'dairy'],
  },

  // ---------- Sides ----------
  'mashed-potatoes-gravy': {
    name: 'Mashed potatoes and gravy',
    description: 'Mashed potatoes with turkey gravy.',
    ingredients: ['russet potatoes', 'butter', 'heavy cream', 'garlic', 'salt', 'white pepper', 'turkey gravy (pan drippings, all-purpose flour, stock)'],
    allergens: ['dairy', 'wheat'],
    note: 'Mushroom gravy available on request.',
    source: 'thanksgiving-2026',
  },
  'au-gratin': {
    name: 'Au gratin potatoes',
    description: 'Sliced Yukon Golds baked in cream with Gruyère and sharp cheddar.',
    ingredients: ['Yukon Gold potatoes', 'heavy cream', 'Gruyère', 'sharp cheddar', 'butter', 'all-purpose flour', 'garlic', 'nutmeg', 'black pepper'],
    allergens: ['dairy', 'wheat'],
    source: 'thanksgiving-2026',
  },
  'seafood-salad': {
    name: 'Seafood salad',
    description: 'Shrimp and crab with celery, red onion and bell pepper in a lemony Old Bay mayonnaise.',
    ingredients: ['shrimp', 'crab', 'celery', 'red onion', 'bell pepper', 'mayonnaise', 'lemon juice', 'Old Bay', 'fresh parsley', 'black pepper'],
    allergens: ['shellfish', 'eggs'],
    note: 'Prepared separately from the rest of the menu.',
    source: 'thanksgiving-2026',
  },
  mac: {
    name: 'Baked mac and cheese',
    description:
      'Sharp cheddar, Colby Jack and cream cheese, baked until golden.',
    ingredients: [
      'elbow macaroni',
      'sharp cheddar',
      'Colby Jack',
      'cream cheese',
      'evaporated milk',
      'butter',
      'eggs',
      'salt',
      'black pepper',
      'paprika',
    ],
    allergens: ['dairy', 'wheat', 'eggs'],
    source: 'thanksgiving-2026',
  },
  collards: {
    name: 'Collard greens',
    description: 'Collard greens cooked with smoked turkey, onion, garlic and cider vinegar.',
    ingredients: [
      'collard greens',
      'smoked turkey',
      'onion',
      'garlic',
      'chicken stock',
      'apple cider vinegar',
      'red pepper flakes',
      'sugar',
      'black pepper',
    ],
    allergens: [],
    note: 'Vegetarian on request: vegetable stock and smoked paprika, no turkey.',
    source: 'thanksgiving-2026',
  },
  yams: {
    name: 'Candied yams',
    description:
      'Sweet potatoes baked in butter, brown sugar, cinnamon, nutmeg, vanilla and orange juice until the syrup turns glossy.',
    ingredients: ['sweet potatoes', 'butter', 'brown sugar', 'cinnamon', 'nutmeg', 'vanilla', 'orange juice', 'salt'],
    allergens: ['dairy'],
    source: 'thanksgiving-2026',
  },
  'green-beans': {
    name: 'Green beans with smoked turkey',
    description: 'Fresh green beans cooked down with smoked turkey, onion, garlic and butter.',
    ingredients: ['fresh green beans', 'smoked turkey', 'onion', 'garlic', 'chicken stock', 'butter', 'black pepper'],
    allergens: ['dairy'],
    source: 'thanksgiving-2026',
  },
  cabbage: {
    name: 'Cabbage',
    description: 'Green cabbage cooked down with smoked turkey, onion, bell pepper, garlic and butter.',
    ingredients: ['green cabbage', 'smoked turkey', 'onion', 'bell pepper', 'garlic', 'butter', 'chicken stock', 'black pepper'],
    allergens: ['dairy'],
    note: 'Vegetarian on request: olive oil and vegetable stock, no turkey.',
    source: 'thanksgiving-2026',
  },
  stuffing: {
    name: 'Stuffing',
    description: 'Cornbread and white bread with celery, onion, sage and thyme, baked until the top goes brown.',
    ingredients: [
      'cornbread and white bread',
      'celery',
      'onion',
      'butter',
      'eggs',
      'chicken stock',
      'fresh sage',
      'thyme',
      'poultry seasoning',
      'black pepper',
    ],
    allergens: ['wheat', 'dairy', 'eggs'],
    source: 'thanksgiving-2026',
  },
  cranberry: {
    name: 'Cranberry sauce',
    description: 'Fresh cranberries cooked down with sugar, orange zest and juice, and cinnamon.',
    ingredients: ['fresh cranberries', 'sugar', 'orange zest and juice', 'cinnamon'],
    allergens: [],
    source: 'thanksgiving-2026',
  },

  // ---------- Bread ----------
  cornbread: {
    name: 'Cornbread',
    description: 'Yellow cornmeal and buttermilk with a little sugar, baked golden.',
    ingredients: ['yellow cornmeal', 'all-purpose flour', 'buttermilk', 'eggs', 'butter', 'sugar', 'baking powder', 'salt'],
    allergens: ['wheat', 'dairy', 'eggs'],
    source: 'thanksgiving-2026',
  },
  rolls: {
    name: 'Dinner rolls',
    description: 'Soft rolls made with milk, butter and eggs.',
    ingredients: ['all-purpose flour', 'milk', 'butter', 'eggs', 'yeast', 'sugar', 'salt'],
    allergens: ['wheat', 'dairy', 'eggs'],
    source: 'thanksgiving-2026',
  },

  // ---------- Desserts ----------
  'pound-cake': {
    name: 'Pound cake',
    description: 'A dense butter cake made with heavy cream, vanilla and a little lemon zest.',
    ingredients: ['all-purpose flour', 'butter', 'sugar', 'eggs', 'heavy cream', 'vanilla', 'lemon zest', 'salt'],
    allergens: ['wheat', 'dairy', 'eggs'],
    source: 'thanksgiving-2026',
  },
  'vanilla-cake': {
    name: 'Vanilla cake',
    description: 'Buttermilk vanilla cake with vanilla buttercream.',
    ingredients: ['all-purpose flour', 'butter', 'sugar', 'eggs', 'buttermilk', 'vanilla', 'baking powder', 'vanilla buttercream'],
    allergens: ['wheat', 'dairy', 'eggs'],
    source: 'thanksgiving-2026',
  },
  'sweet-potato-pie': {
    name: 'Sweet potato pie',
    description: 'Sweet potatoes whipped with evaporated milk, eggs, butter, cinnamon, nutmeg and vanilla in an all-butter crust.',
    ingredients: ['sweet potatoes', 'evaporated milk', 'eggs', 'butter', 'sugar', 'cinnamon', 'nutmeg', 'vanilla', 'all-butter pie crust'],
    allergens: ['dairy', 'eggs', 'wheat'],
    source: 'thanksgiving-2026',
  },

};

export function dish(id) {
  const d = dishes[id];
  if (!d) throw new Error(`Unknown dish id "${id}"`);
  return { id, ...d };
}
