// Every dish on the site, defined once.
// Menus (menus.mjs) and the holiday page (holiday.mjs) point at these by id,
// so a dish's ingredients and allergens can't drift between pages.
//
// `allergens` must match what's in `ingredients`. `node tools/check.mjs`
// scans the ingredient text for allergen words and fails if the two disagree.
//
// Allergen names: dairy, eggs, wheat, shellfish, fish, tree nuts, peanuts, soy, sesame.

// Shared sub-recipes, so they read the same everywhere.
const MAYO = 'mayonnaise (canola oil, egg yolks, distilled vinegar, lemon juice, salt)';
const HOT_SAUCE = 'hot sauce (aged cayenne peppers, distilled vinegar, salt, garlic)';
const CHICKEN_STOCK = 'chicken stock (chicken bones, water, onion, carrot, celery)';
const TURKEY_STOCK = 'turkey stock (turkey bones, water, onion, carrot, celery)';
const CAJUN = 'Cajun seasoning (paprika, garlic, onion, cayenne, oregano, thyme, black pepper, salt)';
const BBQ_SAUCE =
  'vinegar barbecue sauce (apple cider vinegar, ketchup, brown sugar, molasses, yellow mustard, crushed red pepper)';
const PIE_CRUST = 'all-butter crust (all-purpose wheat flour, butter, ice water, sugar, salt)';
const CORNBREAD =
  'skillet cornbread (yellow cornmeal, all-purpose wheat flour, buttermilk, eggs, butter, sugar, baking powder, baking soda, salt)';

export const dishes = {
  // ---------- Mains ----------
  'short-ribs': {
    name: 'Braised short ribs',
    description:
      'Bone-in short ribs seared dark, then braised four hours with onion, carrot, garlic and thyme until a fork goes straight through. Finished in their own gravy.',
    ingredients: [
      'bone-in beef short ribs',
      'yellow onion',
      'carrots',
      'celery',
      'garlic',
      'tomato paste',
      'beef stock (beef bones, water, onion, carrot, celery)',
      'fresh thyme',
      'bay leaf',
      'all-purpose wheat flour',
      'canola oil',
      'kosher salt',
      'black pepper',
      'scallions',
    ],
    allergens: ['wheat'],
  },
  'baked-chicken': {
    name: 'Baked or grilled chicken',
    description:
      'Bone-in chicken rubbed with garlic, lemon, rosemary and paprika, then baked or grilled, your choice. Simple, and a good option next to the richer dishes.',
    ingredients: [
      'bone-in chicken thighs and breasts',
      'olive oil',
      'garlic',
      'lemon',
      'fresh rosemary',
      'fresh thyme',
      'paprika',
      'onion powder',
      'kosher salt',
      'black pepper',
    ],
    allergens: [],
  },
  'lemon-salmon': {
    name: 'Lemon herbed salmon',
    description: 'Salmon fillets roasted with lemon, garlic, dill and parsley, finished with a little butter.',
    ingredients: [
      'Atlantic salmon',
      'lemon',
      'garlic',
      'fresh dill',
      'parsley',
      'fresh thyme',
      'olive oil',
      'butter',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['fish', 'dairy'],
  },
  'surf-and-turf': {
    name: 'Surf and turf',
    description: 'Seared sirloin, sliced, next to shrimp sautéed in garlic butter with lemon and a little Cajun spice.',
    ingredients: [
      'beef sirloin',
      'shrimp',
      'butter',
      'garlic',
      'lemon',
      'parsley',
      CAJUN,
      'olive oil',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['shellfish', 'dairy'],
  },
  'cajun-shrimp': {
    name: 'Cajun butter shrimp',
    description: 'Shrimp cooked in a skillet of butter, garlic, Cajun spice and lemon, with parsley on top. Bread on the side for the sauce.',
    ingredients: ['shrimp', 'butter', 'garlic', CAJUN, 'smoked paprika', 'lemon', 'parsley', 'scallions'],
    allergens: ['shellfish', 'dairy'],
  },
  'fried-chicken': {
    name: 'Honey butter fried chicken',
    description:
      'Bone-in thighs and drumsticks, brined overnight in buttermilk and hot sauce, dredged twice and fried in small batches. Brushed with honey butter as it comes out of the oil.',
    ingredients: [
      'chicken thighs and drumsticks',
      'buttermilk',
      HOT_SAUCE,
      'all-purpose wheat flour',
      'cornstarch',
      'kosher salt',
      'black pepper',
      'smoked paprika',
      'garlic powder',
      'onion powder',
      'cayenne pepper',
      'canola oil for frying',
      'butter',
      'honey',
    ],
    allergens: ['dairy', 'wheat'],
  },
  'smothered-chicken': {
    name: 'Smothered chicken',
    description:
      'Chicken thighs browned in a skillet, then simmered in onion and pepper gravy until the meat is tender. Served over white rice.',
    ingredients: [
      'bone-in chicken thighs',
      'yellow onion',
      'green bell pepper',
      'garlic',
      'all-purpose wheat flour',
      CHICKEN_STOCK,
      'butter',
      'canola oil',
      'poultry seasoning',
      'smoked paprika',
      'fresh thyme',
      'kosher salt',
      'black pepper',
      'long-grain white rice',
    ],
    allergens: ['dairy', 'wheat'],
  },
  'smothered-pork-chops': {
    name: 'Smothered pork chops',
    description:
      'Bone-in center-cut chops, seasoned, dredged and pan-fried, then simmered in onion gravy until a knife goes through without trying.',
    ingredients: [
      'bone-in pork chops',
      'yellow onion',
      'garlic',
      'all-purpose wheat flour',
      CHICKEN_STOCK,
      'butter',
      'canola oil',
      'smoked paprika',
      'garlic powder',
      'onion powder',
      'fresh thyme',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['dairy', 'wheat'],
  },
  'fried-fish': {
    name: 'Southern fried fish',
    description:
      'Whiting or catfish fillets soaked in mustard and hot sauce, dredged in seasoned cornmeal and fried until the crust crackles. Lemon and house tartar sauce on the side.',
    ingredients: [
      'whiting or catfish fillets',
      'yellow mustard',
      HOT_SAUCE,
      'yellow cornmeal',
      'all-purpose wheat flour',
      CAJUN,
      'canola oil for frying',
      'lemon',
      `tartar sauce (${MAYO}, dill relish, lemon juice, onion, parsley)`,
    ],
    allergens: ['fish', 'eggs', 'wheat'],
  },
  'chicken-sandwich': {
    name: 'Fried chicken sandwich',
    description:
      'A boneless thigh brined in buttermilk, fried crisp and set on a toasted brioche bun with dill pickles and hot honey mayo.',
    ingredients: [
      'boneless chicken thighs',
      'buttermilk',
      HOT_SAUCE,
      'all-purpose wheat flour',
      'cornstarch',
      'kosher salt',
      'black pepper',
      'smoked paprika',
      'canola oil for frying',
      'brioche bun (wheat flour, eggs, butter, whole milk, sugar, yeast, salt)',
      'dill pickles',
      `hot honey mayo (${MAYO}, honey, hot sauce)`,
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  'black-eyed-pea-bowl': {
    name: 'Black-eyed pea bowl',
    description:
      'Black-eyed peas stewed with tomato, peppers, thyme and smoked paprika, over white rice with braised cabbage. No meat, no dairy.',
    ingredients: [
      'black-eyed peas',
      'long-grain white rice',
      'crushed tomatoes',
      'yellow onion',
      'green bell pepper',
      'celery',
      'garlic',
      'fresh thyme',
      'smoked paprika',
      'vegetable stock (water, onion, carrot, celery)',
      'green cabbage',
      'olive oil',
      'apple cider vinegar',
      'kosher salt',
      'black pepper',
    ],
    allergens: [],
  },
  'lemon-pepper-wings': {
    name: 'Lemon pepper wings',
    description: 'Whole wings dusted in seasoned flour, fried crisp and tossed in lemon pepper butter while they are still hot.',
    ingredients: [
      'chicken wings',
      'all-purpose wheat flour',
      'cornstarch',
      'canola oil for frying',
      'butter',
      'lemon zest',
      'lemon juice',
      'cracked black pepper',
      'garlic powder',
      'kosher salt',
    ],
    allergens: ['dairy', 'wheat'],
  },
  'honey-hot-wings': {
    name: 'Honey hot wings',
    description: 'Fried wings tossed in hot sauce, honey and butter. Sticky, a little sweet, with real heat at the end.',
    ingredients: [
      'chicken wings',
      'all-purpose wheat flour',
      'cornstarch',
      'canola oil for frying',
      HOT_SAUCE,
      'honey',
      'butter',
      'garlic',
      'cayenne pepper',
      'kosher salt',
    ],
    allergens: ['dairy', 'wheat'],
  },
  'pulled-pork-sliders': {
    name: 'Pulled pork sliders',
    description:
      'Pork shoulder smoked low overnight and pulled by hand, tossed in vinegar barbecue sauce and piled on soft rolls with coleslaw.',
    ingredients: [
      'pork shoulder',
      'brown sugar',
      'paprika',
      'garlic powder',
      'onion powder',
      'kosher salt',
      'black pepper',
      BBQ_SAUCE,
      'slider rolls (wheat flour, whole milk, butter, eggs, sugar, yeast, salt)',
      `coleslaw (green cabbage, carrot, ${MAYO}, apple cider vinegar, sugar, celery seed)`,
    ],
    allergens: ['wheat', 'dairy', 'eggs'],
  },
  'roast-turkey': {
    name: 'Herb-roasted turkey',
    description:
      'A whole bird dry-brined for two days, rubbed with sage and thyme butter under the skin and roasted until the skin is deep brown. Whole or carved, your choice.',
    ingredients: [
      'whole turkey',
      'kosher salt',
      'butter',
      'garlic',
      'fresh sage',
      'fresh thyme',
      'fresh rosemary',
      'black pepper',
      'yellow onion',
      'celery',
      'lemon',
    ],
    allergens: ['dairy'],
  },
  'smoked-turkey': {
    name: 'Smoked turkey',
    description: 'Brined overnight, rubbed with brown sugar and paprika and smoked over hickory for about six hours.',
    ingredients: [
      'whole turkey',
      'kosher salt',
      'brown sugar',
      'paprika',
      'garlic powder',
      'onion powder',
      'black pepper',
      'cayenne pepper',
      'canola oil',
      'hickory wood smoke',
    ],
    allergens: [],
  },
  ham: {
    name: 'Honey-glazed ham',
    description:
      'A bone-in spiral ham glazed with honey, brown sugar, Dijon and pineapple, dressed with pineapple rings and cherries, and baked until the glaze sets and the edges go dark.',
    ingredients: [
      'bone-in spiral ham (pork, water, salt, sugar, sodium nitrite)',
      'honey',
      'brown sugar',
      'Dijon mustard',
      'pineapple juice',
      'pineapple rings',
      'maraschino cherries',
      'ground cloves',
      'butter',
    ],
    allergens: ['dairy'],
  },
  'turkey-wings': {
    name: 'Smothered turkey wings',
    description: 'Turkey wings baked low until tender, then smothered in onion and sage gravy. Good over rice.',
    ingredients: [
      'turkey wings',
      'yellow onion',
      'celery',
      'garlic',
      'all-purpose wheat flour',
      CHICKEN_STOCK,
      'butter',
      'fresh sage',
      'fresh thyme',
      'smoked paprika',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['dairy', 'wheat'],
  },

  // ---------- Brunch ----------
  'shrimp-and-grits': {
    name: 'Shrimp and grits',
    description:
      'Stone-ground grits with white cheddar and butter, under shrimp cooked with peppers, onion and Cajun spice in a pan gravy.',
    ingredients: [
      'shrimp',
      'stone-ground white grits',
      'white cheddar',
      'butter',
      'heavy cream',
      CHICKEN_STOCK,
      'yellow onion',
      'green bell pepper',
      'garlic',
      'all-purpose wheat flour',
      CAJUN,
      'smoked paprika',
      'scallions',
      'lemon',
    ],
    allergens: ['shellfish', 'dairy', 'wheat'],
  },
  'chicken-and-waffles': {
    name: 'Chicken and waffles',
    description: 'Our fried chicken on a buttermilk waffle, with warm maple syrup and butter.',
    ingredients: [
      'chicken thighs and drumsticks',
      'buttermilk',
      HOT_SAUCE,
      'all-purpose wheat flour',
      'cornstarch',
      'kosher salt',
      'black pepper',
      'smoked paprika',
      'canola oil for frying',
      'buttermilk waffles (all-purpose wheat flour, buttermilk, eggs, butter, sugar, baking powder, baking soda, vanilla extract, salt)',
      'maple syrup',
      'butter',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  omelettes: {
    name: 'Cooked-to-order omelettes',
    description:
      'An omelette station: guests choose their fillings and we cook each one in front of them. Cheddar, peppers, onion, spinach, tomato, mushrooms, turkey sausage or ham.',
    ingredients: [
      'eggs',
      'butter',
      'cheddar',
      'green and red bell peppers',
      'yellow onion',
      'spinach',
      'tomatoes',
      'mushrooms',
      'turkey sausage (turkey, salt, sage, black pepper, red pepper)',
      'ham (pork, water, salt, sugar, sodium nitrite)',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['eggs', 'dairy'],
  },
  'mini-quiche': {
    name: 'Handmade mini quiche',
    description: 'Two-bite quiches in an all-butter crust. Spinach and cheddar, or ham and Swiss.',
    ingredients: [
      PIE_CRUST,
      'eggs',
      'heavy cream',
      'whole milk',
      'spinach',
      'cheddar',
      'Swiss cheese',
      'ham (pork, water, salt, sugar, sodium nitrite)',
      'yellow onion',
      'nutmeg',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },

  // ---------- Small bites ----------
  'shrimp-grits': {
    name: 'Shrimp and grits cups',
    description:
      'Stone-ground grits with white cheddar and butter, topped with a seared shrimp and a little smoked paprika butter. Two bites.',
    ingredients: [
      'shrimp',
      'stone-ground white grits',
      'white cheddar',
      'butter',
      'heavy cream',
      CHICKEN_STOCK,
      'garlic',
      'smoked paprika',
      CAJUN,
      'lemon',
      'scallions',
    ],
    allergens: ['shellfish', 'dairy'],
  },
  'fried-green-tomatoes': {
    name: 'Fried green tomatoes',
    description: 'Green tomatoes cut thick, dipped in buttermilk and egg, crusted in cornmeal and fried. Topped with comeback sauce.',
    ingredients: [
      'green tomatoes',
      'buttermilk',
      'eggs',
      'yellow cornmeal',
      'all-purpose wheat flour',
      CAJUN,
      'canola oil for frying',
      `comeback sauce (${MAYO}, chili sauce, ketchup, Worcestershire sauce (contains anchovy), hot sauce, garlic, onion, black pepper)`,
    ],
    allergens: ['dairy', 'eggs', 'wheat', 'fish'],
  },
  'deviled-eggs': {
    name: 'Deviled eggs',
    description: 'Yolks whipped with mayonnaise, mustard and sweet relish. Finished with smoked paprika and chives.',
    ingredients: [
      'eggs',
      MAYO,
      'yellow mustard',
      'sweet pickle relish',
      'apple cider vinegar',
      'smoked paprika',
      'chives',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['eggs'],
  },

  // ---------- Sides ----------
  'mashed-potatoes': {
    name: 'Mashed potatoes',
    description: 'Yukon Gold potatoes mashed with butter, cream and roasted garlic. Left a little rustic.',
    ingredients: ['Yukon Gold potatoes', 'butter', 'heavy cream', 'whole milk', 'roasted garlic', 'chives', 'kosher salt', 'black pepper'],
    allergens: ['dairy'],
  },
  'mixed-vegetables': {
    name: 'Mixed vegetables',
    description: 'Broccoli, carrots, squash, zucchini and red peppers, roasted with olive oil and garlic.',
    ingredients: ['broccoli', 'carrots', 'yellow squash', 'zucchini', 'red bell pepper', 'red onion', 'olive oil', 'garlic', 'kosher salt', 'black pepper'],
    allergens: [],
  },
  mac: {
    name: 'Five-cheese baked macaroni',
    description:
      'Sharp cheddar, white cheddar, Colby Jack, smoked Gouda and cream cheese, set in a custard of eggs and evaporated milk. Baked in the pan we serve it in, so the corners go crisp.',
    ingredients: [
      'elbow macaroni (durum wheat semolina)',
      'sharp cheddar',
      'white cheddar',
      'Colby Jack',
      'smoked Gouda',
      'cream cheese',
      'evaporated milk',
      'whole milk',
      'eggs',
      'butter',
      'dry mustard',
      'smoked paprika',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  collards: {
    name: 'Collard greens with smoked turkey',
    description:
      'Washed three times, cut into ribbons and simmered for three hours with smoked turkey necks, onion and a splash of cider vinegar. No pork.',
    ingredients: [
      'collard greens',
      'smoked turkey necks',
      'yellow onion',
      'garlic',
      CHICKEN_STOCK,
      'apple cider vinegar',
      'crushed red pepper',
      'brown sugar',
      'kosher salt',
      'black pepper',
    ],
    allergens: [],
  },
  yams: {
    name: 'Candied yams',
    description:
      'Sweet potatoes sliced thick and baked in butter, brown sugar, cinnamon, nutmeg and orange zest until the syrup turns glossy.',
    ingredients: [
      'sweet potatoes',
      'butter',
      'brown sugar',
      'granulated sugar',
      'cinnamon',
      'nutmeg',
      'orange zest',
      'vanilla extract',
      'kosher salt',
    ],
    allergens: ['dairy'],
  },
  'green-beans': {
    name: 'Southern green beans',
    description: 'Fresh green beans and red potatoes cooked down slow with smoked turkey and onion.',
    ingredients: [
      'green beans',
      'red new potatoes',
      'smoked turkey',
      'yellow onion',
      'garlic',
      CHICKEN_STOCK,
      'crushed red pepper',
      'kosher salt',
      'black pepper',
    ],
    allergens: [],
  },
  'potato-salad': {
    name: 'Potato salad',
    description: 'Russet potatoes, chopped boiled egg, celery, red onion and sweet relish, folded with mayonnaise and mustard. Paprika on top.',
    ingredients: [
      'russet potatoes',
      'eggs',
      MAYO,
      'yellow mustard',
      'sweet pickle relish',
      'celery',
      'red onion',
      'apple cider vinegar',
      'paprika',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['eggs'],
  },
  'baked-beans': {
    name: 'Baked beans',
    description: 'Navy beans baked with brown sugar, molasses, mustard and smoked turkey until the sauce goes thick and dark.',
    ingredients: [
      'navy beans',
      'smoked turkey',
      'yellow onion',
      'green bell pepper',
      'brown sugar',
      'molasses',
      'ketchup',
      'yellow mustard',
      'apple cider vinegar',
      'garlic',
      'kosher salt',
      'black pepper',
    ],
    allergens: [],
  },
  cabbage: {
    name: 'Fried cabbage',
    description: 'Green cabbage cooked down in a wide skillet with smoked turkey, onion and plenty of black pepper.',
    ingredients: [
      'green cabbage',
      'smoked turkey',
      'yellow onion',
      'garlic',
      'canola oil',
      'crushed red pepper',
      'kosher salt',
      'black pepper',
    ],
    allergens: [],
  },
  'hoppin-john': {
    name: "Hoppin' John",
    description:
      "Black-eyed peas simmered with smoked turkey, onion and thyme, folded into white rice. Eaten on New Year's Day for luck.",
    ingredients: [
      'black-eyed peas',
      'long-grain white rice',
      'smoked turkey',
      'yellow onion',
      'green bell pepper',
      'celery',
      'garlic',
      'fresh thyme',
      'bay leaf',
      CHICKEN_STOCK,
      'crushed red pepper',
      'kosher salt',
      'black pepper',
    ],
    allergens: [],
  },
  'house-salad': {
    name: 'House salad',
    description:
      'Romaine and mixed greens with cucumber, grape tomatoes, red onion, shredded carrot and cornbread croutons. Buttermilk ranch on the side.',
    ingredients: [
      'romaine',
      'mixed greens',
      'cucumber',
      'grape tomatoes',
      'red onion',
      'carrot',
      `cornbread croutons (${CORNBREAD}, butter)`,
      `buttermilk ranch (buttermilk, ${MAYO}, sour cream, garlic, dill, parsley, chives, lemon juice, salt, black pepper)`,
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  dressing: {
    name: 'Cornbread dressing',
    description:
      'Crumbled skillet cornbread with celery, onion, sage and turkey stock, baked until it sets and the top goes brown.',
    ingredients: [
      CORNBREAD,
      'white bread (wheat flour, water, yeast, sugar, salt)',
      'celery',
      'yellow onion',
      'green bell pepper',
      'eggs',
      TURKEY_STOCK,
      'butter',
      'fresh sage',
      'fresh thyme',
      'poultry seasoning',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  gravy: {
    name: 'Turkey gravy',
    description: 'Roasted turkey drippings and a dark roux, thinned with turkey stock and seasoned with sage and black pepper.',
    ingredients: [
      'roasted turkey drippings',
      TURKEY_STOCK,
      'butter',
      'all-purpose wheat flour',
      'fresh sage',
      'fresh thyme',
      'kosher salt',
      'black pepper',
    ],
    allergens: ['dairy', 'wheat'],
  },
  cranberry: {
    name: 'Cranberry sauce',
    description: 'Whole cranberries cooked with orange juice, zest and a cinnamon stick until they pop.',
    ingredients: ['cranberries', 'sugar', 'orange juice', 'orange zest', 'cinnamon stick', 'salt'],
    allergens: [],
  },

  // ---------- Bread ----------
  cornbread: {
    name: 'Skillet cornbread',
    description: 'Yellow cornmeal and buttermilk baked in cast iron and cut into wedges. Honey butter on the side.',
    ingredients: [
      'yellow cornmeal',
      'all-purpose wheat flour',
      'buttermilk',
      'eggs',
      'butter',
      'sugar',
      'baking powder',
      'baking soda',
      'kosher salt',
      'honey',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  rolls: {
    name: 'Yeast rolls',
    description: 'Soft pull-apart rolls, baked the morning of and brushed with melted butter.',
    ingredients: ['all-purpose wheat flour', 'whole milk', 'butter', 'eggs', 'sugar', 'yeast', 'kosher salt'],
    allergens: ['dairy', 'eggs', 'wheat'],
  },

  // ---------- Desserts ----------
  'peach-cobbler': {
    name: 'Peach cobbler',
    description:
      'Sliced peaches cooked down with brown sugar, cinnamon and nutmeg under a buttery biscuit top. Served warm.',
    ingredients: [
      'peaches',
      'brown sugar',
      'granulated sugar',
      'butter',
      'all-purpose wheat flour',
      'whole milk',
      'baking powder',
      'cinnamon',
      'nutmeg',
      'vanilla extract',
      'lemon juice',
      'kosher salt',
    ],
    allergens: ['dairy', 'wheat'],
  },
  'banana-pudding': {
    name: 'Banana pudding',
    description:
      'Stovetop vanilla custard layered with sliced bananas and vanilla wafers we bake ourselves. Whipped cream on top.',
    ingredients: [
      'whole milk',
      'eggs',
      'sugar',
      'cornstarch',
      'butter',
      'vanilla extract',
      'bananas',
      'vanilla wafers (all-purpose wheat flour, butter, sugar, eggs, vanilla extract, baking powder, salt)',
      'heavy cream',
      'kosher salt',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  'pound-cake': {
    name: 'Lemon pound cake',
    description: 'A dense butter cake with lemon zest all the way through and a lemon glaze that cracks when you cut it.',
    ingredients: [
      'butter',
      'sugar',
      'eggs',
      'all-purpose wheat flour',
      'whole milk',
      'lemon zest',
      'lemon juice',
      'vanilla extract',
      'baking powder',
      'kosher salt',
      'powdered sugar',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  'red-velvet-cupcakes': {
    name: 'Red velvet cupcakes',
    description: 'Buttermilk red velvet with cream cheese frosting piped high.',
    ingredients: [
      'all-purpose wheat flour',
      'sugar',
      'buttermilk',
      'eggs',
      'canola oil',
      'cocoa powder',
      'red food coloring (Red 40)',
      'white vinegar',
      'baking soda',
      'vanilla extract',
      'salt',
      'cream cheese',
      'butter',
      'powdered sugar',
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  'sweet-potato-pie': {
    name: 'Sweet potato pie',
    description: 'Roasted sweet potatoes whipped with butter, evaporated milk, nutmeg and vanilla, baked in an all-butter crust.',
    ingredients: [
      'sweet potatoes',
      'butter',
      'evaporated milk',
      'eggs',
      'sugar',
      'brown sugar',
      'nutmeg',
      'cinnamon',
      'vanilla extract',
      'salt',
      PIE_CRUST,
    ],
    allergens: ['dairy', 'eggs', 'wheat'],
  },
  'pecan-pie': {
    name: 'Pecan pie',
    description: 'Toasted pecans in a brown sugar and butter filling, baked in an all-butter crust until the center just sets.',
    ingredients: ['pecans', 'eggs', 'brown sugar', 'corn syrup', 'butter', 'vanilla extract', 'salt', PIE_CRUST],
    allergens: ['tree nuts', 'dairy', 'eggs', 'wheat'],
  },

  // ---------- Drinks ----------
  'sweet-tea': {
    name: 'Sweet tea',
    description: 'Black tea brewed strong and sweetened while it is still hot. Lemon on the side.',
    ingredients: ['water', 'black tea', 'cane sugar', 'lemon'],
    allergens: [],
  },
  lemonade: {
    name: 'Fresh lemonade',
    description: 'Squeezed lemons, cane sugar and water.',
    ingredients: ['fresh lemon juice', 'cane sugar', 'water'],
    allergens: [],
  },
};

export function dish(id) {
  const d = dishes[id];
  if (!d) throw new Error(`Unknown dish id "${id}"`);
  return { id, ...d };
}
