import { View } from 'react-native';

import { useTheme } from '@/theme';

import { AppText } from './AppText';

/** The ✦ marker. Every AI feature shows this so people always know when AI is involved. */
export function AIMark({ label = 'AI' }: { label?: string }) {
  return (
    <View accessible accessibilityLabel={`${label}, generated by AI`} style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}>
      <AppText variant="label" tone="ai">
        ✦ {label}
      </AppText>
    </View>
  );
}

/** Paid placements are always labeled. Never disguised. */
export function SponsoredLabel({ kind = 'Sponsored' }: { kind?: 'Sponsored' | 'Featured' }) {
  const t = useTheme();
  return (
    <View
      accessible
      accessibilityLabel={kind}
      style={{
        alignSelf: 'flex-start',
        backgroundColor: t.colors.sponsored,
        borderRadius: t.radius.sm,
        paddingHorizontal: t.space[2],
        paddingVertical: 2,
      }}>
      <AppText variant="caption" weight="bold" style={{ color: t.colors.onSponsored, letterSpacing: 0.8 }}>
        {kind.toUpperCase()}
      </AppText>
    </View>
  );
}
